/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function callAltThreadFunc(tsfn: ((err: Error | null, ) => any)): void

export declare function generateClientCertificate(clientId: string, clientName: string, rootCa: string, rootCaPrivate: string): Array<string>

export declare function generateManifest(dir: string, progressSfn: ((err: Error | null, arg: number) => any), logSfn: ((err: Error | null, arg: string) => any), callbackSfn: ((err: Error | null, arg: string) => any)): void

export declare function generateRootCa(): Array<string>

export declare function hasBackendForPath(path: string): boolean

export declare function listFiles(path: string): Array<string>

export declare function readFile(path: string, subPath: string): ReadableStream<Buffer> | null

export declare function signNonce(privateKey: string, nonce: string): string

export declare function verifyClientCertificate(clientCert: string, rootCa: string): boolean

export declare function verifyNonce(publicCert: string, nonce: string, signature: string): boolean
