/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Script {

}

export declare class ScriptEngine {
  constructor()
  buildRhaiScript(content: string): Script
  buildJsScript(content: string): Script
  execute(script: Script): void
  fetchStrings(script: Script): Array<string>
}

export declare function callAltThreadFunc(tsfn: ((err: Error | null, ) => any)): void

export declare function generateClientCertificate(clientId: string, clientName: string, rootCa: string, rootCaPrivate: string): Array<string>

export declare function generateManifest(dir: string, progressSfn: ((err: Error | null, arg: number) => any), logSfn: ((err: Error | null, arg: string) => any)): Promise<string>

export declare function generateRootCa(): Array<string>

export declare function hasBackendForPath(path: string): boolean

export declare function listFiles(path: string): Promise<Array<string>>

export declare function peekFile(path: string, subPath: string): Promise<bigint>

export declare function readFile(path: string, subPath: string, start?: bigint | undefined | null, end?: bigint | undefined | null): ReadableStream<Buffer>

export declare function signNonce(privateKey: string, nonce: string): string

export declare function verifyClientCertificate(clientCert: string, rootCa: string): boolean

export declare function verifyNonce(publicCert: string, nonce: string, signature: string): boolean
